"""Create trips table

Revision ID: 178cd456a05a
Revises: 
Create Date: 2026-08-23 01:23:57.974795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178cd456a05a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('travelers', sa.Integer(), nullable=False),
    sa.Column('budget', sa.String(length=50), nullable=True),
    sa.Column('travel_style', sa.String(length=100), nullable=True),
    sa.Column('interests', sa.JSON(), nullable=True),
    sa.Column('itinerary', sa.JSON(), nullable=True),
    sa.Column('estimated_cost', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trips')
    # ### end Alembic commands ###
