"""add user region column

Revision ID: a5b6c7d8e9f0
Revises: d4e5f6a7b8c9
Create Date: 2026-08-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a5b6c7d8e9f0'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_country', sa.String(length=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_region_country'), ['region_country'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_region_country'))
        batch_op.drop_column('region_country')
    # ### end Alembic commands ###
