"""add subscriptions table and user region column

Revision ID: a5b6c7d8e9f0
Revises: d4e5f6a7b8c9
Create Date: 2026-08-30 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a5b6c7d8e9f0'
down_revision = 'd4e5f6a7b8c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_country', sa.String(length=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_users_region_country'), ['region_country'], unique=False)

    op.create_table(
        'subscriptions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('tier', sa.String(length=20), nullable=False),
        sa.Column('period', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('store', sa.String(length=20), nullable=True),
        sa.Column('store_product_id', sa.String(length=255), nullable=True),
        sa.Column('store_transaction_id', sa.String(length=255), nullable=True),
        sa.Column('active_until', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
    )
    op.create_index(op.f('ix_subscriptions_store_transaction_id'), 'subscriptions', ['store_transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscriptions_store_transaction_id'), table_name='subscriptions')
    op.drop_table('subscriptions')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_region_country'))
        batch_op.drop_column('region_country')
    # ### end Alembic commands ###
